name: Sync to GitHub

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove workflow files to avoid permission error
        run: rm -rf .github/workflows

      - name: Push to GitHub
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote add github https://x-access-token:$GH_TOKEN@github.com/anbeime/solar.git
          git push github master --force
